name: BeTheMob
version: 1.11
main: com.lenis0012.bukkit.btm.BeTheMob
authors: [lenis0012, bowser123467]
softdepend: [ProtocolLib]
commands:
  btm:
    description: BeTheMob main command.
    usage: /btm mob <mob type>