name: BeTheMob
version: 2.0
main: com.lenis0012.bukkit.btm.BeTheMob
authors: [lenis0012]
depend: [BKCommonLib]
commands:
  btm:
    description: BeTheMob main command.
    usage: /btm
    aliases: [disguise, dis, d]
